- name: create temp dir for bindep
  tempfile:
    state: directory
    prefix: bindep
  register: bindep_temp_dir
  notify:
    - remove bindep temp dir

- name: install bindep into temporary venv
  pip:
    name: bindep
    virtualenv: "{{ bindep_temp_dir.path }}/venv"

- name: Define bindep_command
  set_fact:
    bindep_command: "{{ bindep_temp_dir.path }}/venv/bin/bindep"
