---
- include: find.yaml
  when: bindep_file is not defined

- include: find-bindep.yaml
  when: bindep_file is defined

- include: install.yaml
  when: bindep_command is not defined

- name: Define bindep_run fact
  set_fact:
    bindep_run: "{{ bindep_command }} -b -f {{ bindep_file }} {{ bindep_profile }}"
  when: bindep_file is defined

- include: packages.yaml
  when: bindep_file is defined
