- include: common.yaml

# Note (dmsimard)
# We explicitely declare a PATH environment variable because '/sbin' is not in
# PATH when using 'become: yes' on some distributions
- include: switch.yaml
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"
  when: inventory_hostname in groups['switch']
  static: no

- include: peer.yaml
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"
  when: inventory_hostname in groups['peers']
  static: no

- name: Persist iptables rules
  include_role:
    name: persistent-firewall
