- name: Install chromium-brower
  apt:
    name: chromium-browser
  become: true

- name: Install xvfb
  apt:
    name: xvfb
  become: true

- name: Run Xvfb
  shell: "/usr/bin/Xvfb :99 -screen 0 '1280x1024x24' -ac +extension GLX +render -noreset 2>&1 > /dev/null &"
